name: interview-booking-app
services:
- name: api
  source_dir: backend
  github:
    repo: your-username/interview-booking-project
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"
  - key: MONGODB_URI
    value: ${MONGODB_URI}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: FRONTEND_URL
    value: ${FRONTEND_URL}
  - key: CORS_ORIGIN
    value: ${CORS_ORIGIN}

static_sites:
- name: frontend
  source_dir: frontend
  github:
    repo: your-username/interview-booking-project
    branch: main
  build_command: npm run build
  output_dir: dist
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
  envs:
  - key: VITE_API_URL
    value: ${API_URL}
  - key: VITE_APP_NAME
    value: MockAce
